### PR TITLE
Add support for additional params in ghhops-server (params.py)

### PR DESCRIPTION
**Pull request by fstwn**
### Changes

- Add wrapper for `GH_Plane` to `ghhops-server`

### Testing & Verification

- Verified to work with `rhinoinside` as well as `rhino3dm`
- Can be tested to work by defining the following hops component:
```
@hops.component(
    "/paramtest.Plane",
    name="ptPlane",
    nickname="ptPlane",
    description="Test Plane Param.",
    category=None,
    subcategory=None,
    inputs=[
        hs.HopsPlane("InPlane", "I", "Input Plane.", hs.HopsParamAccess.ITEM), # NOQA501
    ],
    outputs=[
        hs.HopsPlane("OutPlane", "O", "Output Plane.", hs.HopsParamAccess.ITEM), # NOQA501
    ])
def paramtest_PlaneComponent(in_plane):

    if not in_plane:
        return Rhino.Geometry.Plane.WorldXY
    return in_plane
```
verify_plane

### Notes

Hey there,
another attempt at contributing to `ghhops-server`. I will be adding more param wrappers as I need them in developing a component server. This project is part of my PhD research and will also be open source very soon. Since I want to work with it also during workshops with students, I would really appreciate it if these PR's could be reviewed and merged soon. 

The reason for my continuous bugging (sorry...) is: I would like to avoid confronting the students with a modded `ghhops-server` version or cumbersome tailor made setup-scripts (like it is currently) for reasons of simplicity. A lot of them are not experienced python developers (or programmers at all) and installing a working, official package from PyPi is much easier to comprehend than going into the source files or similar.

If you have made it this far reading this text, thank you for your time and consideration!
Best,
Max

### CODE REVIEW

**Comment by fstwn** [comment]
### Changes

- Add wrapper for `GH_Plane` to `ghhops-server`

### Testing & Verification

- **ONLY WORKS WITH RHINOINSIDE** because [`rhino3dm.Geometry.Circle` has no support for Planes whatsoever (lol)](https://mcneel.github.io/rhino3dm/python/api/Circle.html)
- Can be tested to work by defining the following hops component:
```
@hops.component(
    "/paramtest.Circle",
    name="ptCircle",
    nickname="ptCircle",
    description="Test Circle Param.",
    category=None,
    subcategory=None,
    icon="resources/icons/220204_malt_icon.png",
    inputs=[
        hs.HopsCircle("InCircle", "I", "Input Circle.", hs.HopsParamAccess.ITEM), # NOQA501
    ],
    outputs=[
        hs.HopsCircle("OutCircle", "O", "Output Circle.", hs.HopsParamAccess.ITEM), # NOQA501
    ])
def paramtest_CircleComponent(in_cicle):

    if not in_cicle:
        return Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY,
                                     1.0)
    return in_cicle
```
verify_circle

**Comment by sbaer** [comment]
Thanks @fstwn ; I'm trying to figure out if I can get a Circle constructor written that takes a plane as input into rhino3dm so we don't have to throw an exception

**Comment by fstwn** [comment]
That would be ace! I'm currently looking into the Hops C# implementation to see how we can enable more param types. Still have to learn a lot but that's the recording thing about it I guess :)

**Comment by sbaer** [comment]
I'm adding a `Circle.Plane` property that can be used to set a plane. Our rhino3dm CI build system seems to be having issues at the moment. Hopefully we can get that cleared up next week.
https://github.com/mcneel/rhino3dm/pull/450

**Comment by sbaer** [comment]
rhino3dm 7.14 now should support setting a circle's plane. I would suggest we update this PR to use this new property
https://github.com/mcneel/compute.rhino3d/blob/master/src/ghhops-server-py/Pipfile

**Comment by fstwn** [comment]
Thanks for the effort Steve! I will get going on updating the code and PR accordingly right now since I have bit of spare time :)

**Comment by fstwn** [comment]
### Changes

- Update wrapper for `GH_Circle` to `ghhops-server`

### Testing & Verification

- Now also works with `rhino3dm` thanks to the new `Circle.Plane` property.
- Verified to work with `rhinoinside` as well as `rhino3dm`
- Can be tested to work by defining the following hops component:
```
@hops.component(
    "/paramtest.Circle",
    name="ptCircle",
    nickname="ptCircle",
    description="Test Circle Param.",
    category=None,
    subcategory=None,
    inputs=[
        hs.HopsCircle("InCircle", "I", "Input Circle.", hs.HopsParamAccess.ITEM), # NOQA501
    ],
    outputs=[
        hs.HopsCircle("OutCircle", "O", "Output Circle.", hs.HopsParamAccess.ITEM), # NOQA501
    ])
def paramtest_CircleComponent(in_cicle):

    if not in_cicle:
        return Rhino.Geometry.Circle(Rhino.Geometry.Plane.WorldXY,
                                     1.0)
    return in_cicle
```
verify_circle_v2

**Comment by fstwn** [comment]
Hey,
just checking in. @sbaer could you take a quick look at this again?
Thank you in advance <3

**Pull request merged**
