### PR TITLE
Fix error that occurs when stream is closed before getting Length value

### PR DESCRIPTION
**Pull request by tarabishy2020**
When using the python-api an error is thrown when creating the "ResponseContentLength" property.
The stream is disposed before exiting the using block. This is a workaround.

### CODE REVIEW

**Comment by tarabishy2020** [comment]
@pearswj @sbaer figured sth else out instead of a try and catch block

**Comment by pearswj** [comment]
Thanks Sherif! I’ve been busy with the AEC Tech hackathon, but I’ll get this merged next week 👍

**Comment by sbaer** [comment]
I don't understand what this is fixing. Could you provide a sample of the python problem that you were seeing?

**Comment by pearswj** [comment]
Hey @tarabishy2020. Sorry, I should have merged this last year when it was relevant... We're now recommending that people ignore the compute.frontend project and run compute.geometry directly, with their own ["application server"](https://github.com/mcneel/compute.rhino3d.appserver) between the user and compute.

**Pull request closed without merging**
