### PR TITLE
Add PS script to update Rhino WIP

### PR DESCRIPTION
**Pull request by tarabishy2020**
Add a Powershell script to update Rhino WIP. 

Useful as a scheduled task before the current version expires.

### CODE REVIEW

**Comment by sbaer** [comment]
Please make the file name all lower case. I would also remove the WIP from this as we will eventually just use this to update rhino after the WIP period.

**Comment by tarabishy2020** [comment]
Shall we check if the version we will download is newer than what is installed before actually downloading?

**Comment by sbaer** [comment]
That would make a lot of sense. I'm beginning to wonder if new versions are already getting downloaded via our automatic updates system.

@golsby do we have a way to check if the installed Rhino matches the one that would be downloaded from `"https://www.rhino3d.com/download/rhino-for-windows/7/wip/direct?email=$Email`

**Comment by tarabishy2020** [comment]
I assumed the script is going to run on Windows.

**Comment by sbaer** [comment]
oh, I see you already fixed this check in your script :) I was confused. Thanks for the PR. Merging now

**Pull request merged**
